### ISSUE TITLE
pdfinfo.exe で日本語表示を可能にする方法は？

### ISSUE THREAD

**Issue by samurai-jp** [HiraokaHyperTools/ypdfeditor#11]
はじめまして。
先に、基礎知識の部分があまりないのでトンチンカンな質問の内容になるかもしれません。
また、ypdfeditorとは直接関係無い内容にもなっています。他に聞ける日本語向けサイトが無いのでコチラに質問をさせて頂きます。それをお許し下さい。m(＿.＿)m

「pdfinfo.exe -enc xxx」で2バイト文字部分の表示を制御したいと思っています。
そこで、Popplerから言語サポートパッケージ poppler-data-0.4.7.tar.gz をダウンロードして参照できるように設定をXpdfを参考にしましたが、うまく出来ません。
（Xpdf では言語ファイルを参照出来るように出来ました。）

poppler-data.pc 又はpoppler-data.pc.in の内容を動作環境のパスに変更しましたが、やはりダメでした。

```
poppler_datadir=I:\Tools\Run\Poppler-0.45\bin

Name: poppler-data
Description: Encoding files for use with poppler
Version: 0.4.7

Cflags: -DPOPPLER_DATADIR=I:\Tools\Run\Poppler-0.45\bin
```

環境：　Windows 10 64bit 
Poppler version ：　0.45
Poppler Windows 版ダウンロード先：http://blog.alivate.com.au/poppler-windows/
Poppler DATAダウンロード先：http://www.linuxfromscratch.org/blfs/view/svn/general/poppler.html

Poppler のフォントパッケージを実行時に扱えるようにするにはどこをどのような設定にしたらよいのでしょうか。
解説しているURL等でのご紹介でも構いません。

お手数を掛けます。よろしくお願いいたします。

**Comment by kenjiuno** [comment]
お世話になります。

私もさほど詳しくないのであれですが、poppler-0.45/share の中に poppler-data の poppler フォルダを入れてはいかがでしょうか。

**Comment by samurai-jp** [comment]
出来ました！
海外のサイトを検索したり、イロイロと20日以上も悪戦苦闘してました。
もう、諦めかけていた時にタマタマ、コチラが検索であたって、失礼と思いながらも質問させて頂きました。

ありがとうございました。
本当に助かりました！

**Comment by kenjiuno** [comment]
解決して何よりです（＾＾
